export *  from "./Collections/CollectionsPage.jsx";
export * from "./Home/HomePage.jsx";
export * from "./Image/ImagePage.jsx";
export * from "./Images/ImagesPage.jsx";
export * from "./Login/LoginPage.jsx";
export * from "./NotFound/NotFoundPage.jsx";
export * from "./Profile/ProfilePage.jsx";
export * from "./Register/RegisterPage.jsx";
export * from "./Upload/UploadPage.jsx";
