USE `spottedwebsdb`;

CREATE TABLE IF NOT EXISTS `User` (
  `userId` BIGINT PRIMARY KEY AUTO_INCREMENT,
  `username` VARCHAR(255) UNIQUE NOT NULL,
  `hashedPassword` VARCHAR(255) NOT NULL,
  `createdAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS `UserProfile` (
  `userProfileId` BIGINT PRIMARY KEY AUTO_INCREMENT,
  `profilePicture` VARCHAR(255) UNIQUE,
  `firstName` VARCHAR(255),
  `lastName` VARCHAR(255),
  `userId` BIGINT NOT NULL,
  `createdAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (`userId`) REFERENCES `User` (`userId`) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS `AccessToken` (
  `tokenId` BIGINT PRIMARY KEY AUTO_INCREMENT,
  `userId` BIGINT NOT NULL,
  `token` VARCHAR(512) NOT NULL,
  `secretKey` VARCHAR(512) NOT NULL,
  `createdAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (`userId`) REFERENCES `User` (`userId`) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS `RefreshToken` (
  `tokenId` BIGINT PRIMARY KEY AUTO_INCREMENT,
  `userId` BIGINT NOT NULL,
  `token` VARCHAR(512) UNIQUE NOT NULL,
  `secretKey` VARCHAR(512) UNIQUE NOT NULL,
  `createdAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (`userId`) REFERENCES `User` (`userId`) ON DELETE CASCADE
  );

  CREATE TABLE IF NOT EXISTS `TokenBlacklist` (
    `tokenId` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `userId` BIGINT NOT NULL,
    `token` VARCHAR(512) UNIQUE NOT NULL,
    `revokedAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (`userId`) REFERENCES `User` (`userId`) ON DELETE CASCADE
  );

CREATE TABLE IF NOT EXISTS `Image` (
  `imageId` BIGINT PRIMARY KEY AUTO_INCREMENT,
  `image` VARCHAR(255) UNIQUE NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `userId` BIGINT NOT NULL,
  `createdAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updatedAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  FOREIGN KEY (`userId`) REFERENCES `User` (`userId`) ON DELETE CASCADE
  );

CREATE TABLE IF NOT EXISTS `Collection` (
    `collectionId` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `thumbnail` VARCHAR(255) UNIQUE NOT NULL,
    `title` VARCHAR(255) NOT NULL,
    `subtitle` VARCHAR(255) NOT NULL,
    `blurb` TEXT NOT NULL,
    `userId` BIGINT NOT NULL,
    `createdAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updatedAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (`userId`) REFERENCES `User` (`userId`) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS `ImageCollection` (
    `imageCollectionId` BIGINT PRIMARY KEY AUTO_INCREMENT,
    `imageId` BIGINT NOT NULL,
    `collectionId` BIGINT NOT NULL,
    `createdAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    `updatedAt` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (`imageId`) REFERENCES `Image` (`imageId`) ON DELETE CASCADE,
    FOREIGN KEY (`collectionId`) REFERENCES `Collection` (`collectionId`) ON DELETE CASCADE
);
